# version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  db_data:
